// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// runNet
// [[Rcpp::export]]
List runNet(const StringVector& nodeData,
    const NumericVector & runs,
    const NumericVector & steps);


RcppExport SEXP vanillaBn_runNet(SEXP nodeDataSEXP,
                                 SEXP runsSEXP,
                                 SEXP stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const StringVector& >::type nodeData(nodeDataSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type runs(runsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type steps(stepsSEXP);
    __result = Rcpp::wrap(runNet(nodeData, runs, steps));
    return __result;
END_RCPP
}
