// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP vanillaBn_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}

// runNet
List runNet(const StringVector& nodeData,
            const NumericVector & runs,
            const NumericVector & steps);
RcppExport SEXP vanillaBn_runNet(SEXP nodeDataSEXP,
                                 SEXP runsSEXP,
                                 SEXP stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const StringVector& >::type nodeData(nodeDataSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type runs(runsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type steps(stepsSEXP);
    __result = Rcpp::wrap(runNet(nodeData, runs, steps));
    return __result;
END_RCPP
}
