# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('vanillaBn_rcpp_hello_world', PACKAGE = 'vanillaBn')
}


runNet <- function(nodeData, runs, steps) {
    .Call('vanillaBn_runNet', PACKAGE='vanillaBn', nodeData, runs, steps);
}
